version: '3.9'

services:

    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=project
            - POSTGRES_PASSWORD=project
            - POSTGRES_DB=SequenceProDB
        ports:
            - '5040:5040'