// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sequence_Pro.Application.Database;

#nullable disable

namespace Sequence_Pro.Application.Migrations
{
    [DbContext(typeof(SequenceProContext))]
    [Migration("20230925174629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sequence_Pro.Application.Database.Models.SequenceAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AminoAcidComposition")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<double>("MolecularWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("ProteinSequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceLength")
                        .HasColumnType("integer");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SequenceAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
