// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SequencePro.Application.Database;

#nullable disable

namespace SequencePro.Application.Migrations
{
    [DbContext(typeof(SequenceProContext))]
    [Migration("20231019104325_AACompositionTable")]
    partial class AACompositionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sequence_Pro.Application.Database.Models.AminoAcidComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("AminoAcid")
                        .HasColumnType("character(1)");

                    b.Property<double>("Proportion")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SequenceAnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SequenceAnalysisId");

                    b.ToTable("AminoAcidComposition");
                });

            modelBuilder.Entity("Sequence_Pro.Application.Database.Models.SequenceAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("MolecularWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("ProteinSequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceLength")
                        .HasColumnType("integer");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SequenceAnalyses");
                });

            modelBuilder.Entity("Sequence_Pro.Application.Database.Models.AminoAcidComposition", b =>
                {
                    b.HasOne("Sequence_Pro.Application.Database.Models.SequenceAnalysisEntity", null)
                        .WithMany("AminoAcidCompositions")
                        .HasForeignKey("SequenceAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sequence_Pro.Application.Database.Models.SequenceAnalysisEntity", b =>
                {
                    b.Navigation("AminoAcidCompositions");
                });
#pragma warning restore 612, 618
        }
    }
}
